FROM node:18 as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .n
ENV NODE_ENV production
RUN npm run build
FROM nginx:alpine
COPY --from=build /app/build /usr/share/nginx/html
EXPOSE 80s
CMD ["nginx", "-g", "daemon off;"]
